- name: mouse / keyboard config
  become: yes
  become_user: sjas
  copy:
    src: kcminputrc
    dest: /home/sjas/.config

- name: en / de keyboard layouts + en_US
  become: yes
  become_user: sjas
  copy:
    src: "{{ item }}"
    dest: /home/sjas/.config
  with_items:
    - kxkbrc
    - plasma-localerc