---

- name: set widget config
  become: yes
  become_user: sjas
  copy:
    src: plasma-org.kde.plasma.desktop-appletsrc
    dest: /home/sjas/.config

- name: set holiday regions
  become: yes
  become_user: sjas
  copy:
    src: plasma_calendar_holiday_regions
    dest: /home/sjas/.config
