---

- name: install devilspie
  apt:
    cache_valid_time: 7200
    name:
      - devilspie2

- name: ensure config folder exists
  file:
    dest: /home/sjas/.devilspie
    state: directory
    owner: sjas
    group: sjas
