---

- name: install devilspie2
  apt:
    cache_valid_time: 7200
    name:
      - devilspie2

- name: ensure config folder exists
  file:
    dest: /home/sjas/.config/devilspie2/
    state: directory
    owner: sjas
    group: sjas

- name: ensure systemd user folder exists
  file:
    dest: /home/sjas/.config/systemd/user/
    state: directory
    owner: sjas
    group: sjas

- name: deploy devilspie2 systemd unit file
  copy:
    src: devilspie2.service
    dest: /home/sjas/.config/systemd/user/
    owner: sjas
    group: sjas

- name: systemd daemon reload
  become: yes
  become_user: sjas
  systemd:
    daemon_reload: yes
    scope: user

- name: enable and start systemd service
  become: yes
  become_user: sjas
  systemd:
    name: devilspie2.service
    scope: user
    state: restarted
  changed_when: false
