---

- name: deploy bettercap
  become: yes
  become_user: sjas
  copy:
    src: bettercap
    dest: /home/sjas/.local/bin
    mode: 0744

- name: install bettercap dependency
  apt:
    name: libnetfilter-queue1
