- name: config rollout
  copy: src={{ item }} dest=/home/sjas/etc/.dotfiles/
  with_items:
    - .bashrc_env
    - .bashrc_aliases
    - .bashrc_git
    - .bashrc_completion

- name: reference configs from .bashrc
  lineinfile: path=/home/sjas/.bashrc line=". /home/sjas/etc/.ansible/roles/bash/files/{{ item }}"
  with_items:
    - .bashrc_env
    - .bashrc_aliases
    - .bashrc_git
    - .bashrc_completion

- name: direnv hook
  lineinfile: path=/home/sjas/.bashrc line='eval "$(direnv hook bash)"'

- name: reference .bashrc_includes if present
  lineinfile: path=/home/sjas/.bashrc line="[ -f /home/sjas/etc/.dotfiles/.bashrc_includes ] && . /home/sjas/etc/.dotfiles/.bashrc_includes"

- name: fix git default settings
  command:
    git config --global {{ item }}
  with_items:
    - color.ui                            "true"
    - color.diff-highlight.oldNormal      "red bold"
    - color.diff-highlight.oldHighlight   "red bold 52"
    - color.diff-highlight.newNormal      "green bold"
    - color.diff-highlight.newHighlight   "green bold 22"
    - color.diff.meta                     "yellow"
    - color.diff.frag                     "magenta bold"
    - color.diff.commit                   "yellow bold"
    - color.diff.old                      "red bold"
    - color.diff.new                      "green bold"
    - color.diff.whitespace               "red reverse"
    - push.default                        "matching"
    - user.name                           "sjas"
