---

- name: microsoft apt-key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: add vscode repo
  apt_repository:
    repo: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode

- name: install vscode package
  apt:
    name: code
    state: present
    update_cache: yes

- name: vscode extension install check
  become: yes
  become_user: sjas
  ignore_errors: true
  shell: |
    code --list-extensions |
    grep \
    -e DavidAnson.vscode-markdownlint \
    -e Rubymaniac.vscode-direnv \
    -e jamiewoodio.junos \
    -e jpogran.puppet-vscode \
    -e ms-python.python \
    -e ms-vscode.Go \
    -e redhat.vscode-yaml \
    -e ryanolsonx.zenburn \
    -e vscoss.vscode-ansible \
    -e yhirose.FilterText \
    -e samuelcolvin.jinjahtml \
    -e austin.code-gnu-global \
    -e mitaki28.vscode-clang \
    -e ms-vscode.cpptools \
    -e wwm.better-align \
    -e ryu1kn.partial-diff \
    -e Yummygum.city-lights-icon-vsc \
    -e korekontrol.saltstack \
    | wc -l
  register: vsc_plugin_count
  changed_when: false

- name: set current vscode plugin count
  command: echo 18
  register: vsc_plugin_count_desired
  changed_when: false

- name: stop vscode because microsoft cant build software properly
  shell: pkill -9 code && echo 0 || echo 1
  register: vscode_stopped
  ignore_errors: true
  when: not vsc_plugin_count.stdout is search( "{{ vsc_plugin_count_desired.stdout }}" )
  changed_when: false

- name: install vscode extensions if not present
  become: yes
  become_user: sjas
  command: code --install-extension {{ item }}
  with_items:
    - DavidAnson.vscode-markdownlint
    - jamiewoodio.junos
    - jpogran.puppet-vscode
    - ms-python.python
    - ms-vscode.go
    - redhat.vscode-yaml
    - ryanolsonx.zenburn
    - vscoss.vscode-ansible
    - yhirose.FilterText
    - Rubymaniac.vscode-direnv
    - samuelcolvin.jinjahtml
    - austin.code-gnu-global
    - mitaki28.vscode-clang
    - ms-vscode.cpptools
    - wwm.better-align
    - ryu1kn.partial-diff
    - Yummygum.city-lights-icon-vsc
    - korekontrol.saltstack
  when: not vsc_plugin_count.stdout is search( "{{ vsc_plugin_count_desired.stdout }}" )
  tags:
    - dont_lint_this

- name: set vscode configuration
  become: yes
  become_user: sjas
  copy:
    src: settings.json
    dest: /home/sjas/.config/Code/User/settings.json

- name: set vscode keybindings for code navigation
  become: yes
  become_user: sjas
  copy:
    src: keybindings.json
    dest: /home/sjas/.config/Code/User/

- name: start vscode if it was stopped
  become: yes
  become_user: sjas
  command: code
  delegate_to: localhost
  when: not vsc_plugin_count.stdout is search("{{ vsc_plugin_count_desired.stdout }}") and vscode_stopped.stdout == "0"
  changed_when: false
