---

- name: register nvm install script name
  become: yes
  become_user: sjas
  command: echo v0.34.0
  register: nvm_installer_version
  changed_when: false

- name: register current node version to be used
  become: yes
  become_user: sjas
  command: echo v11.12.0
  register: nodejs_version
  changed_when: false

- name: make sure destination folder exists
  become: yes
  become_user: sjas
  file:
    path: "/home/sjas/.nvm"
    state: directory

- name: get nvm
  become: yes
  become_user: sjas
  shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/{{ nvm_installer_version.stdout }}/install.sh | bash
  args:
    creates: "/home/sjas/.nvm/nvm.sh"

- name: clean NVM_DIR var from .bashrc
  lineinfile:
    path: /home/sjas/.bashrc
    regex: "export NVM_DIR.*"
    state: absent

- name: always purge OS nodejs if exists
  apt:
    purge: yes
    state: absent
    name:
      - nodejs
      - nodejs-doc

- name: check if node.js {{ nodejs_version.stdout }} is already installed
  become: yes
  become_user: sjas
  shell: NVM_DIR=/home/sjas/.nvm . /home/sjas/.nvm/nvm.sh && nvm ls {{ nodejs_version.stdout }}
  register: exitcode_nodejs_install
  ignore_errors: true
  changed_when: false

- name: install node.js {{ nodejs_version.stdout }}
  become: yes
  become_user: sjas
  shell: NVM_DIR=/home/sjas/.nvm . /home/sjas/.nvm/nvm.sh && nvm install {{ nodejs_version.stdout }}
  when: exitcode_nodejs_install.rc != 0
  notify: node_shell_relogin

- name: set node.js {{ nodejs_version.stdout }} as default
  become: yes
  become_user: sjas
  shell: NVM_DIR=/home/sjas/.nvm . /home/sjas/.nvm/nvm.sh && nvm alias default {{ nodejs_version.stdout }}
  when: exitcode_nodejs_install.rc != 0
  notify: node_shell_relogin

- name: get path current nodejs for setcap'ing
  shell: find /home/sjas/.nvm/versions/node/ -type f -iname node | grep {{ nodejs_version.stdout }}
  register: nodejs_path
  changed_when: false

- name: setcap on current nodejs so it can open ports 1024
  capabilities:
    path: "{{ nodejs_path.stdout }}"
    cap: "CAP_NET_BIND_SERVICE=+ep"
  when: nodejs_path.rc == 0
  changed_when: false
