---

- name: google apt-key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: google-chrome repo
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome

- name: chrome dependencies
  apt:
    update_cache: yes
    name:
      - fonts-liberation
      - libappindicator3-1
      - libindicator3-7

- name: google-chrome package
  apt:
    name: google-chrome-stable
    cache_valid_time: 1800
