- name: get firefox profile folder path
  shell: ls /home/sjas/.mozilla/firefox/*default -d
  register: ff_path
  changed_when: false
  tags: asdf

- name: deploy firefox settings
  become: yes
  become_user: sjas
  copy:
    src: user.js
    dest: "{{ ff_path.stdout }}"
  tags: asdf