---

- name: chromium
  include: 0x01_chromium.yml
  tags: chromium

- name: google-chrome
  include: 0x02_google-chrome.yml
  tags: chrome

- name: firefox
  include: 0x03_firefox.yml
  tags: firefox

- name: brave
  include: 0x04_brave.yml
  tags: brave
