---

- name: install libvirt and virt-manager packages
  apt:
    cache_valid_time: 1800
    name:
      - qemu
      - qemu-utils
      - libvirt-bin
      - virtinst
      - unrar-free
      - libguestfs-tools
      - libosinfo-bin

- name: ensure libvirtd group exists
  group:
    name: libvirtd

- name: make user part of libvirtd group
  user:
    name: sjas
    append: yes
    groups: libvirtd
