---

- name: etckeeper first
  apt: name={{ item }} cache_valid_time=1800
  with_items:
    - etckeeper

- name: basic packages from upstream
  apt: name={{ item }} autoclean=yes autoremove=yes update_cache=yes
  with_items:
    - apt-file
    - at
    - atop
    - bash-completion
    - bashdb
    - checkinstall
    - chrony
    - colordiff
    - conntrack
    - curl
    - dhcpdump
    - dhcping
    - diffutils
    - elinks
    - ethstatus
    - exfat-fuse
    - exfat-utils
    - fail2ban
    - filezilla
    - freerdp-x11
    - geoip-bin
    - git-all
    - global
    - golang-1.10
    - haveged
    - hdparm
    - hping3
    - htop
    - httping
    - iftop
    - inxi
    - ioping
    - iotop
    - kdiff3
    - libreoffice
    - lnav
    - iputils-arping
    - ltrace
    - lynx
    - mc
    - meld
    - mlocate
    - multitail
    - mysql-client
    - mytop
    - nicstat
    - nload
    - nmap
    - nmon
    - nomacs
    - openvpn
    - percona-toolkit
    - net-tools
    - ntfs-3g
    - p7zip
    - parallel
    - parted
    - puppet
    - puppet-lint
    - pv
    - pwgen
    - python-optcomplete
    - qmmp
    - rpm2cpio
    - rsync
    - screen
    - scite
    - shellcheck
    - shutter
    - strace
    - sysstat
    - tcpdump
    - thunderbird
    - thunderbird-locale-de
    - tmux
    - traceroute
    - tree
    - uptimed
    - util-linux
    - vim
    - wdiff
    - wget
    - whois
    - whowatch
    - x2x
    - xautomation
    - xbindkeys
    - xbindkeys-config
    - yamllint

- name: basic packages from single .deb files
  apt: deb={{ item }}
  with_items:
    - /home/sjas/etc/.ansible/roles/common/files/fd_7.0.0_amd64.deb
    - /home/sjas/etc/.ansible/roles/common/files/ripgrep_0.8.1_amd64.deb

- name: language packages
  apt: name={{ item }} cache_valid_time=1800
  with_items:
    - aspell-de
    - hunspell-de-de
    - hyphen-de
    - ingerman
    - language-pack-de
    - language-pack-de-base
    - language-pack-gnome-de
    - language-pack-gnome-de-base
    - language-pack-kde-de
    - libreoffice-help-de
    - libreoffice-l10n-de
    - mythes-de
