- name: basic packages
  apt: > 
    name: {{ item }}
    autoclean: yes 
    autoremove: yes
    update_cache: yes
  with_items:
    - apt-file
    - bash-completion
    - curl 
    - ethstatus
    - exfat-fuse
    - exfat-utils
    - filezilla
    - git-all
    - hdparm
    - htop 
    - iftop 
    - iotop
    - mc 
    - mlocate
    - multitail
    - nmap
    - ntfs-3g 
    - p7zip
    - parallel
    - parted
    - python-optcomplete
    - pwgen
    - rsync
    - screen
    - sysstat
    - tcpdump
    - tmux
    - traceroute
    - tree
    - vim 
    - wget 
    - whois
    - xterm
    - xtermcontrol
    - xtermsets