---

- name: etckeeper first
  apt:
    cache_valid_time: 1800
    name:
      - etckeeper

- name: basic packages from upstream
  apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
    name:
      - apt-file
      - aptsh
      - at
      - atop
      - bash-completion
      # - bashdb  ## https://sourceforge.net/projects/bashdb/files/bashdb/4.4-0.93/
      - bison
      - bzr
      - ccze
      - cmake
      - checkinstall
      - chrony
      - colordiff
      - conntrack
      - curl
      - dhcpdump
      - dhcping
      - diffutils
      - dnsmasq
      - dnsmasq-utils
      - docutils-common
      - edac-utils
      - elinks
      - ethstatus
      - exfat-fuse
      - exfat-utils
      - expect
      - ext4magic
      - fail2ban
      - filezilla
      - fio
      - flex
      - flex-doc
      - freerdp-x11
      - geoip-bin
      - git-all
      - global
      - graphviz
      - haveged
      - hdparm
      - hping3
      - htop
      - httping
      - iftop
      - inxi
      - inotify-tools
      - iperf3
      - ioping
      - iotop
      - jq
      - kdiff3
      - leafpad
      - libinput-tools
      - libreoffice
      - libxml2-utils
      - linux-tools-generic
      - lnav
      - iputils-arping
      - ltrace
      - lynx
      - mc
      - meld
      - mlocate
      - moreutils
      - most
      - multitail
      - mysql-client
      - mytop
      - ncdt
      - ncdu
      - network-manager-openvpn
      - nicstat
      - nload
      - nmap
      - nmon
      - nomacs
      - nttcp
      - nuttcp
      - openvpn
      - percona-toolkit
      - pcmanfm
      - powertop
      - pylint
      - python-rope
      - python3-rope
      - pylint3
      - net-tools
      - netperf
      - ntfs-3g
      - p7zip
      - parallel
      - parted
      - pbzip2
      - puppet-lint
      - pv
      - pwgen
      - python-optcomplete
      - qmmp
      - rename
      - rlwrap
      - rpm2cpio
      - rsync
      - ruby-ronn
      - screen
      - scite
      - shellcheck
      - shutter
      - strace
      - subversion
      - sysstat
      - tack
      - tcpdump
      - thunderbird
      - thunderbird-locale-de
      - tldr
      - tmux
      - traceroute
      - tree
      - uptimed
      - util-linux
      - vim
      - w3m
      - wdiff
      - wget
      - whois
      - whowatch
      - x2x
      - xautomation
      - xbindkeys
      - xbindkeys-config
      - xdotool
      - xmlstarlet
      - xserver-xorg-input-libinput
      - yamllint
      - zmap

- name: fd
  apt:
    deb: /home/sjas/etc/.ansible/roles/common/files/fd_7.0.0_amd64.deb
- name: rg
  apt:
    deb: /home/sjas/etc/.ansible/roles/common/files/ripgrep_0.8.1_amd64.deb

# https://itsfoss.com/shutter-edit-button-disabled/
- name: additionally needed shutter package for 18.04 - libgoocanvas-common_1.0.0-1_all.deb
  apt:
    deb: /home/sjas/etc/.ansible/roles/common/files/libgoocanvas-common_1.0.0-1_all.deb

- name: additionally needed shutter package for 18.04 - libgoocanvas3_1.0.0-1_amd64.deb
  apt:
    deb: /home/sjas/etc/.ansible/roles/common/files/libgoocanvas3_1.0.0-1_amd64.deb

- name: additionally needed shutter package for 18.04 - libgoo-canvas-perl_0.06-2ubuntu3_amd64.deb
  apt:
    deb: /home/sjas/etc/.ansible/roles/common/files/libgoo-canvas-perl_0.06-2ubuntu3_amd64.deb

- name: language packages
  apt:
    cache_valid_time: 1800
    name:
      - aspell-de
      - hunspell-de-de
      - hyphen-de
      - ingerman
      - language-pack-de
      - language-pack-de-base
      - language-pack-gnome-de
      - language-pack-gnome-de-base
      - language-pack-kde-de
      - libreoffice-help-de
      - libreoffice-l10n-de
      - mythes-de
