---

- name: etckeeper first
  apt:
    cache_valid_time: 7200
    name:
      - etckeeper

- name: basic packages from upstream
  apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
    name:
      - apt-file
      - apt-rdepends
      - aptsh
      - at
      - atop
      - autossh
      - bash-completion
      - bfs
      # - bashdb  ## https://sourceforge.net/projects/bashdb/files/bashdb/4.4-0.93/ ## not available in 18.04 yet
      - bison
      - byobu
      - bzr
      - ccze
      - cmake
      - checkinstall
      - chrony
      - colordiff
      - conntrack
      - curl
      - dhcpdump
      - dhcping
      - dialog
      - diffutils
      - dnsmasq
      - dnsmasq-utils
      - docutils-common
      - edac-utils
      - elinks
      - ethstatus
      - exfat-fuse
      - exfat-utils
      - expect
      - ext4magic
      - fail2ban
      - filezilla
      - finger
      - firejail
      - fio
      - firefox
      - flex
      - flex-doc
      - fortunes-off
      - freerdp-x11
      - geoip-bin
      - git-all
      - global
      - graphviz
      - haveged
      - hdparm
      - hping3
      - htop
      - httping
      - iftop
      - inxi
      - inotify-tools
      - ioping
      - iotop
      - ipcalc
      - iperf3
      - iptraf
      - jq
      - kde-runtime
      - kdiff3
      - leafpad
      - lft
      - libinput-tools
      - libreoffice
      - libxml2-utils
      - linux-tools-generic
      - lnav
      - iputils-arping
      - ldnsutils
      - lftp
      - ltrace
      - lynx
      - mbuffer
      - mc
      - meld
      - mlocate
      - moreutils
      - most
      - multitail
      - mysql-client
      - mytop
      - ncdt
      - ncdu
      - network-manager-openvpn
      - ngrep
      - nicstat
      - nload
      - nmap
      - nmon
      - nomacs
      - nttcp
      - nuttcp
      - openvpn
      - percol
      - percona-toolkit
      - pcmanfm
      - powertop
      - pylint
      - pylint3
      - python-ipdb
      - python3-ipdb
      - python-pip
      - python3-pip
      - python-pudb
      - python3-pudb
      - python-rope
      - python3-rope
      - pylint3
      - net-tools
      - ntfs-3g
      - p7zip
      - parallel
      - parted
      - patchutils
      - pbzip2
      - puppet-lint
      - pv
      - pwgen
      - python-optcomplete
      - qalc
      - qmmp
      - rename
      - rlwrap
      - rpm2cpio
      - rsync
      - ruby-ronn
      - rxvt-unicode
      - screen
      - scite
      - shellcheck
      - shutter
      - siege
      - sipcalc
      - sngrep
      - snmp
      - snmp-mibs-downloader
      - source-highlight
      - stow
      - strace
      - subversion
      - sysstat
      - tack
      - tcpdump
      - thunderbird
      - thunderbird-locale-de
      - tig
      - tldr
      - tmux
      - traceroute
      - tree
      - tsung
      - tudu
      - units
      - uptimed
      - util-linux
      - vifm
      - vim
      - w3m
      - wdiff
      - wget
      - whois
      - whowatch
      - x2x
      - xautomation
      - xbindkeys
      - xbindkeys-config
      - xdotool
      - xmlstarlet
      - xserver-xorg-input-libinput
      - yamllint
      - yapf
      - yapf3
      - zmap

- name: no ufw allowed here
  apt:
    name: ufw
    state: absent

- name: firewalld
  apt:
    deb: /home/sjas/etc/.ansible/roles/common/files/firewalld_0.6.3-1_all.deb
- name: firewall-config
  apt:
    deb: /home/sjas/etc/.ansible/roles/common/files/firewall-config_0.6.3-1_all.deb
- name: firewall-applet
  apt:
    deb: /home/sjas/etc/.ansible/roles/common/files/firewall-applet_0.6.3-1_all.deb
- name: make sure firewalld uses iptables as backend, because nftables breaks shit
  lineinfile: path=/etc/firewalld/firewalld.conf regex='^FirewallBackend=' line='FirewallBackend=iptables'

- name: fd
  apt:
    deb: /home/sjas/etc/.ansible/roles/common/files/fd_7.0.0_amd64.deb

- name: rg
  apt:
    deb: /home/sjas/etc/.ansible/roles/common/files/ripgrep_0.8.1_amd64.deb

- name: eaglemode
  apt:
    deb: /home/sjas/etc/.ansible/roles/common/files/eaglemode_0.94.0-1_amd64.deb

# https://itsfoss.com/shutter-edit-button-disabled/
- name: additionally needed shutter package for 18.04 - libgoocanvas-common_1.0.0-1_all.deb
  apt:
    deb: /home/sjas/etc/.ansible/roles/common/files/libgoocanvas-common_1.0.0-1_all.deb
- name: additionally needed shutter package for 18.04 - libgoocanvas3_1.0.0-1_amd64.deb
  apt:
    deb: /home/sjas/etc/.ansible/roles/common/files/libgoocanvas3_1.0.0-1_amd64.deb
- name: additionally needed shutter package for 18.04 - libgoo-canvas-perl_0.06-2ubuntu3_amd64.deb
  apt:
    deb: /home/sjas/etc/.ansible/roles/common/files/libgoo-canvas-perl_0.06-2ubuntu3_amd64.deb

- name: language packages
  apt:
    cache_valid_time: 7200
    name:
      - aspell-de
      - hunspell-de-de
      - hyphen-de
      - ingerman
      - language-pack-de
      - language-pack-de-base
      - language-pack-gnome-de
      - language-pack-gnome-de-base
      - language-pack-kde-de
      - libreoffice-help-de
      - libreoffice-l10n-de
      - mythes-de
