- name: etckeeper first
  apt: > 
    name: {{ item }}
    cache_valid_time: 1800
  with_items:
    - etckeeper

- name: basic packages
  apt: name={{ item }} autoclean=yes autoremove=yes update_cache=yes
  with_items:
    - apt-file
    - atop
    - bash-completion
    - bashdb
    - chrony
    - colordiff
    - conntrack
    - csync2
    - curl
    - dhcpdump
    - dhcping
    - diffutils
    - direnv
    - elinks
    - ethstatus
    - exfat-fuse
    - exfat-utils
    - fail2ban
    - filezilla
    - freerdp-x11
    - git-all
    - global
    - golang-1.10
    - haveged
    - hdparm
    - hping3
    - htop 
    - httping
    - iftop 
    - ioping
    - iotop
    - libreoffice
    - lnav
    - iputils-arping
    - lynx
    - mc 
    - mlocate
    - multitail
    - mysql-client
    - mytop
    - nicstat
    - nload
    - nmap
    - nmon
    - openntpd
    - openvpn
    - percona-toolkit
    - ntfs-3g 
    - p7zip
    - parallel
    - parted
    - pv
    - pwgen
    - python-optcomplete
    - rsync
    - screen
    - sysstat
    - tcpdump
    - thunderbird
    - thunderbird-locale-de
    - tmux
    - traceroute
    - tree
    - util-linux
    - vim 
    - wdiff
    - wget 
    - whois
    - whowatch
    - x2x

- name: language packages
  apt: >
    name: {{ item }}
    cache_valid_time: 1800
  with_items:
    - aspell-de
    - hunspell-de-de
    - hyphen-de
    - ingerman
    - language-pack-de
    - language-pack-de-base
    - language-pack-gnome-de
    - language-pack-gnome-de-base
    - language-pack-kde-de
    - libreoffice-help-de
    - libreoffice-l10n-de
    - mythes-de
