- name: directories
  become: yes
  become_user: sjas
  file:
    dest: /home/sjas/{{ item }}
    state: directory
  with_items:
    - wrk
    - prv 
    - txt 
    - etc
    - etc/.dotfiles
    - .config
    - .local
    - .local/bin
    - .dotfiles

- name: symlinks
  become: yes
  become_user: sjas
  file:
    src: /home/sjas/Downloads
    dest: /home/sjas/dl
    state: link