---

- name: deploy mouse scrolling udev rules
  copy:
    src: "{{ item }}"
    dest: /etc/udev/hwdb.d/
    mode: 0744
  with_items:
    - 71-mouse-microsoft.hwdb
    - 72-mouse-yellow.hwdb
  notify: scroll_udev_deploy
