- name: xterm packages
  apt: name={{ item }} cache_valid_time=1800
  with_items:
    - xterm
    - xtermcontrol
    - xtermsets

- name: make xterm shortcuts behave
  become: yes 
  become_user: sjas
  copy:
    - src: .Xresources
    - dest: /home/sjas