- name: xterm packages
  apt: name={{ item }} cache_valid_time=1800
  with_items:
    - xterm
    - xtermcontrol
    - xtermsets

- name: make sure .Xdefaults is present
  become: yes
  become_user: sjas
  command: touch /home/sjas/.Xdefaults
  changed_when: false
  
- name: make xterm shortcuts behave
  lineinfile: path=/home/sjas/.Xdefaults line="xterm*metaSendsEscape:true"