---

- name: xterm packages
  apt: name={{ item }} cache_valid_time=1800
  with_items:
    - xterm
    - xtermcontrol
    - xtermset

- name: make sure .Xdefaults is present
  become: yes
  become_user: sjas
  file:
    dest: /home/sjas/.Xdefaults
    state: touch
  changed_when: false

- name: make xterm shortcuts behave
  become: yes
  become_user: sjas
  lineinfile: dest=/home/sjas/.Xdefaults line="xterm*metaSendsEscape:true"
