- name: xterm packages
  apt: name={{ item }} cache_valid_time=1800
  with_items:
    - xterm
    - xtermcontrol
    - xtermsets

- name: make sure .Xdefaults is present
  become: yes
  become_user: sjas
  file:
    dest: /home/sjas/.Xdefaults
    state: touch

- name: make xterm shortcuts behave
  lineinfile: path=/home/sjas/.Xdefaults line="xterm*metaSendsEscape:true"